// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKihNHPWoZpdkWL9jHDgVOBV01WpplSnQ',
    appId: '1:688787168404:ios:e01bb8eda37ddd8fa8e881',
    messagingSenderId: '688787168404',
    projectId: 'family-market-bd1f4',
    storageBucket: 'family-market-bd1f4.firebasestorage.app',
    iosBundleId: 'com.example.familyMarket',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbaCdIUJuc4NAc3tuPqOFxG0gNHI4leIk',
    appId: '1:688787168404:web:27c62667583f6110a8e881',
    messagingSenderId: '688787168404',
    projectId: 'family-market-bd1f4',
    authDomain: 'family-market-bd1f4.firebaseapp.com',
    storageBucket: 'family-market-bd1f4.firebasestorage.app',
  );

}